/**
 * @file
 * Drupal WxT Bootstrap object.
 */

/**
 * All Drupal cch_wxt ssocca JavaScript APIs are contained in this namespace.
 *
 * @namespace
 */
(function ($, Drupal) {
  'use strict';

  Drupal.behaviors.ssocca = {
    attach: function (context, settings) {
      if (context == document) {
        SsoccaFrontend.init();
        jQuery('body.i18n-en a.french-only').each(function(index, element){
          // For Keyboard navigation fix in English.
          jQuery(element).closest('li').remove();
        });
        jQuery('body.i18n-fr a.english-only').each(function(index, element){
          // For Keyboard navigation fix in French.
          jQuery(element).closest('li').remove();
        });
      }
    }
  }
  Drupal.ssocca = {
    settings: drupalSettings.ssocca || {},
  };

  /**
   * Returns the version of WxT being used.
   *
   * @return {string}
   *   The version of WxT being used.
   */
  Drupal.ssocca.version = 'Cch_wxt v1.0';

  console.log(Drupal.ssocca.version);

})(window.jQuery, window.Drupal, window.drupalSettings);


var SsoccaFrontend = function() {
  var initialized = false;   // Flag to indicate that this class has been initialized
  var lang = 'en';           // Will be 'en' or 'fr' regardless of how the url segment is formed (currently eng or fra)
  var mouse = {x:0, y:0};    // Tracks the mouse position
  var page_type = 'content';

  /**
   * Initialization
   */
  function init() {
    if (initialized) {
      return;
    }

    // Get the current UI language
    $ = jQuery;
    if (SsoccaFrontend.isIE()) {
      $('body').addClass('isIE');
    }

    SsoccaFrontend.lang = $('html').attr('lang');

    //Determine the page type
    if ($('body').hasClass('path-frontpage')) {
      SsoccaFrontend.page_type = 'front'; // Front page <front> ex, /en or /fr.
    }
    else if ($('body').hasClass('path-webform')) {
      SsoccaFrontend.page_type = 'webforms';
    }
    else if ($('body').hasClass('ssocca') && $('body').hasClass('path-node')) {
      SsoccaFrontend.page_type = 'content'; // Content pages generated by ssocca.
    }
    else if ($('body').hasClass('path-admin')) {
      SsoccaFrontend.page_type = 'admin'; // Other admin page.
    }

    removeStutteringTitleAttribute();
    $('#wb-glb-mn a.overlay-lnk').click(function(e) {
      SsoccaFrontend.removeRoleFromSummary(); // WCAG fix.
    });

    initialized = true;
  }


  function isIE() {
    if (navigator.appName == 'Microsoft Internet Explorer') {
      return true;
    }
    else if (navigator.appName == 'Netscape') {
      if (navigator.appVersion.indexOf('Trident') > 0 || navigator.appVersion.indexOf('Edge') > 0) {
        return true;
      }
    }
    return false;
  }


  function removeStutteringTitleAttribute() {
    // WCAG fix, for removing stuttering title attributes.
    var hrefElements = $('a[data-entity-type]').each(function(index, element) {
      var title = $(this).attr('title');
      if (title == $(this).text()) {
        $(this).removeAttr('title');
      }
    });
  }


  function removeRoleFromSummary() {
    // WCAG fix see : https://github.com/wet-boew/GCWeb/issues/1716
    var hrefElements = $('summary.mb-item[role]').each(function(index, element) {
      var role = $(this).attr('role');
      $(this).removeAttr('role');
      $(this).parent().find('li').each(function(idx,el) {
        $(el).attr('role', 'menuitem');
      });
      $(this).closest('li').attr('role', 'menuitem');
    });
  }

  /**
   * Expose functions and variables
   */
  return {
    init: init,
    lang: lang,
    isIE: isIE,
    page_type: page_type,
    removeRoleFromSummary: removeRoleFromSummary
  }
}();

